name: BipolarAI
options:
  bundleIdPrefix: jp.mt-inn
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  BipolarAI:
    type: application
    platform: iOS
    sources:
      - path: BipolarAI
        excludes:
          - "Resources/Assets.xcassets"
          - "Resources/Info.plist"
          - "Resources/BipolarAI.entitlements"
    resources:
      - path: BipolarAI/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jp.mt-inn.bipolarai
        INFOPLIST_FILE: BipolarAI/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: BipolarAI/Resources/BipolarAI.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    entitlements:
      path: BipolarAI/Resources/BipolarAI.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.background-delivery: true
